spring.datasource.url=jdbc:postgresql://localhost:5433/subscription_system
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

otp.expiration-minutes=5

stripe.api-key-hk=${STRIPE_API_KEY_HK}
stripe.api-key-sg=${STRIPE_API_KEY_SG}
stripe.api-key-my=${STRIPE_API_KEY_MY}
stripe.mock-base-url=${STRIPE_MOCK_BASE_URL}
stripe.mock-enabled=${STRIPE_MOCK_ENABLED}
stripe.skipSignatureCheck=${STRIPE_SKIP_SIGNATURE_CHECK}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}


# Send traces to the otel-collector via OTLP/HTTP
management.otlp.tracing.endpoint=http://otel-collector:4318/v1/traces

# Send metrics to the otel-collector via OTLP/HTTP (forwarded to Mimir)
management.otlp.metrics.export.url=http://otel-collector:4318/v1/metrics
management.otlp.metrics.export.step=5s
