spring.datasource.url=jdbc:postgresql://localhost:5432/subscription_system
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

otp.expiration-minutes=5

stripe.api-key-id=${STRIPE_API_KEY_ID}
stripe.api-key-sg=${STRIPE_API_KEY_SG}
stripe.api-key-us=${STRIPE_API_KEY_US}
stripe.mock-base-url=${STRIPE_MOCK_BASE_URL}
stripe.mock-enabled=${STRIPE_MOCK_ENABLED}
stripe.skipSignatureCheck=${STRIPE_SKIP_SIGNATURE_CHECK}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}